In [2]:
import torch

In [ ]:
torch.__version__

In [3]:
import numpy as np

In [4]:
lst=[3,4,5,6]
arr=np.array(lst)

In [ ]:
arr

In [ ]:
arr.dtype

Convert Numpy To Pytorch Tensors


In [ ]:
tensors=torch.from_numpy(arr)
tensors

In [ ]:
### Indexing similar to numpy
tensors[2]

In [ ]:
tensors[1:4]


In [10]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [ ]:
tensors

In [ ]:
arr

In [ ]:
### Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

In [ ]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

In [ ]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

In [ ]:
torch.ones(2,3,dtype=torch.float64)


In [40]:
a=torch.tensor(np.arange(0,15).reshape(5,3))


In [ ]:
a

In [ ]:
a[:,0]


In [ ]:
a[:,0:2]


In [ ]:
a

In [3]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [4]:
torch.add(a,b)


tensor([ 7.,  9., 11.])

In [5]:
c=torch.zeros(3)


In [6]:
c

tensor([0., 0., 0.])

In [7]:
torch.add(a,b,out=c)


tensor([ 7.,  9., 11.])

In [8]:
c

tensor([ 7.,  9., 11.])

In [9]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [10]:
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

Dot Products and Mult Operations


In [11]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [12]:
x.mul(y)


tensor([12., 20., 30.])

In [29]:
### 3*4+5*4+6*5


In [13]:
x.dot(y) 


tensor(62.)

Matrix Multiplication


In [14]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [15]:
torch.matmul(x,y)


tensor([[55., 53.],
        [90., 92.]])

In [16]:
torch.mm(x,y)


tensor([[55., 53.],
        [90., 92.]])

In [17]:
x@y


tensor([[55., 53.],
        [90., 92.]])